insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 123, 'Y', 11111111111, '1', 'José da Silva', 3245678, 2341, 2323, 2323, 2323, 'Zé');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 234, 'Y', 22222222222, '2', 'Paula Tejando', 3445599, 1321, 1123, 2553, 2001, 'Paulinha Asa Fixa');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 345, 'Y', 33333333333, '3', 'Thomás Turbando', 2422599, 1001, 1003, 1153, 1221, 'Turbando');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 1, 'Y', 44444444444, '3', 'Jack Bauer', 242, 1, 1, 11, 11, 'jbauer');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 2, 'Y', 55555555555, '3', 'Daniel Samuel', 2242, 21, 21, 211, 211, 'dsam');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 3, 'Y', 66666666666, '4', 'Thor Odinson', 211, 221, 221, 221, 221, 'thor');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 77777777777, '4', 'Hulk Hogan', 2111, 2121, 2121, 2121, 2211, 'hulk');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 88888888888, '4', 'Domingos de Segunda a Sexta', 5, 5, 5, 5, 5, 'domingos');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 99999999999, '3', 'Chavasca MCinskey', 5, 5, 5, 5, 5, 'xavas');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 12688250264, '3', 'Mauro Morado', 5, 5, 5, 5, 5, 'morado');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 46631295793, '4', 'Elenice Kenga', 5, 5, 5, 5, 5, 'kenga');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 82845484453, '4', 'Gisele Vagabunda', 5, 5, 5, 5, 5, 'givaga');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 42155952155, '4', 'Luiz Lula', 5, 5, 5, 5, 5, 'fdp');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 53983118593, '3', 'Helio Nigga', 5, 5, 5, 5, 5, 'nigga');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 63854406215, '3', 'Chi In Pan Zé', 5, 5, 5, 5, 5, 'china');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 55418667904, '2', 'Dilma Pinto', 5, 5, 5, 5, 5, 'strapon');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 28396346780, '2', 'Dirceu Ladrão', 5, 5, 5, 5, 5, 'ptralha');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 72266517007, '2', 'Denise Furacão', 5, 5, 5, 5, 5, 'pelobuça');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 61850589879, '1', 'Timelo Rêgo', 5, 5, 5, 5, 5, 'regaço');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 48452032609, '2', 'Márcia Ranca Toco', 5, 5, 5, 5, 5, 'ranca toco');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 21832397947, '2', 'Barbie Experian', 5, 5, 5, 5, 5, 'barbie');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 44848942705, '3', 'Irina Ilianenko', 5, 5, 5, 5, 5, 'russa');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 79943633182, '2', 'George Bush', 5, 5, 5, 5, 5, 'cusão');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 83842654707, '1', 'Barack Obama', 5, 5, 5, 5, 5, 'fela');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 49542676417, '4', 'João Kleber', 5, 5, 5, 5, 5, 'crébs');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 87694868244, '4', 'Fausto Silva', 5, 5, 5, 5, 5, 'faustão');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 53433106134, '1', 'Ronaldo Nazário', 5, 5, 5, 5, 5, 'viado');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 81411296435, '1', 'Amilton Milho', 5, 5, 5, 5, 5, 'poetero');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 23768090450, '1', 'Jonnhy Clane', 5, 5, 5, 5, 5, 'johnny');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 63030213285, '1', 'João Marcos', 5, 5, 5, 5, 5, 'jmarcos');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 63817779747, '1', 'João Paulo', 5, 5, 5, 5, 5, 'jpaulo');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 34147244807, '1', 'João Kleber', 5, 5, 5, 5, 5, 'jkleber');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ALUNO_PILOTO', null, 4, 'Y', 25478053678, '1', 'João Celso', 5, 5, 5, 5, 5, 'jcelso');
insert into Aeronave (id, apoliceSeguro, ativo, certificadoMatricula, checkList, dentel, diarioBordo, fiam, fichaPesoBalanceamento, manualVoo, marca, modelo, nsca3_5, nsca3_7) values (null, 123, 'Y', 'PT-NXZ', 234, 'Y', '12', 'Y', 'Y', 'Y', 'Cessna', '172', 'Y', 'Y');
insert into Aeronave (id, apoliceSeguro, ativo, certificadoMatricula, checkList, dentel, diarioBordo, fiam, fichaPesoBalanceamento, manualVoo, marca, modelo, nsca3_5, nsca3_7) values (null, 234, 'Y', 'PR-MRG', 567, 'Y', '33', 'Y', 'Y', 'Y', 'Airbus', 'A300', 'Y', 'Y');
insert into Aeronave (id, apoliceSeguro, ativo, certificadoMatricula, checkList, dentel, diarioBordo, fiam, fichaPesoBalanceamento, manualVoo, marca, modelo, nsca3_5, nsca3_7) values (null, 234, 'Y', 'PT-IZQ', 567, 'Y', '33', 'Y', 'Y', 'Y', 'Piper', 'Cherokee', 'Y', 'Y');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('INSTRUTOR_PILOTO', null, 4, 'Y', 22147244807, '1', 'Santos Dumont', 5, 5, 5, 5, 5, 'dumon');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('INSTRUTOR_PILOTO', null, 4, 'Y', 22147554117, '1', 'Barão Vermelho', 5, 5, 5, 5, 5, 'redbaron');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('INSTRUTOR_PILOTO', null, 4, 'Y', 22147247717, '1', 'Bregaida Jr.', 5, 5, 5, 5, 5, 'bregaidajr');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('SOCIO_PILOTO', null, 4, 'Y', 22147248887, '1', 'Bregaida Sr.', 5, 5, 5, 5, 5, 'panda');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('SOCIO_PILOTO', null, 4, 'Y', 11017248887, '1', 'Bola Gato', 5, 5, 5, 5, 5, 'ballcat');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ATENDENTE', null, 4, 'Y', 11147242887, '1', 'Monica', 5, 5, 5, 5, 5, 'monabola');
insert into Pessoa (PESSOA_TYPE, id, alistamentoMilitar, ativo, cpf, escolaridade, nome, rg, tituloEleitor, cht, cma, codigoANAC, nomePista) values ('ATENDENTE', null, 4, 'Y', 11147348887, '1', 'Valéria', 5, 5, 5, 5, 5, 'valdelicia');
insert into Aula (id,materia, quantidadeHorasNecessarias) values (null,'Manobras Altas', 50);
insert into Aula (id,materia, quantidadeHorasNecessarias) values (null,'TGL', 200);
insert into Aula (id,materia, quantidadeHorasNecessarias) values (null,'Aperfeiçoamento', 250);
insert into Aula (id,materia, quantidadeHorasNecessarias) values (null,'INVA', 300);
insert into Aula (id,materia, quantidadeHorasNecessarias) values (null,'Acrobática', 500);
insert into aula_aeronave (aula_id, aeronave_id) values (1, 1);
insert into aula_aeronave (aula_id, aeronave_id) values (1, 2);
insert into aula_aeronave (aula_id, aeronave_id) values (1, 3);
insert into aula_aeronave (aula_id, aeronave_id) values (2, 1);
insert into aula_aeronave (aula_id, aeronave_id) values (2, 2);
insert into aula_aeronave (aula_id, aeronave_id) values (2, 3);
insert into aula_aeronave (aula_id, aeronave_id) values (3, 1);
insert into aula_aeronave (aula_id, aeronave_id) values (3, 2);
insert into aula_aeronave (aula_id, aeronave_id) values (3, 3);
insert into aula_aeronave (aula_id, aeronave_id) values (4, 1);
insert into aula_aeronave (aula_id, aeronave_id) values (4, 2);
insert into aula_aeronave (aula_id, aeronave_id) values (4, 3);
insert into aula_aeronave (aula_id, aeronave_id) values (5, 1);
insert into aula_aeronave (aula_id, aeronave_id) values (5, 2);
insert into aula_aeronave (aula_id, aeronave_id) values (5, 3);
